<?php


define('KWSQL',
       
["and" => "AND",
 "or" => "OR",
 "not" => "NOT",
 "bt" => "BETWEEN",
 "order" => "\nORDER BY",
 "group" =>"\nGROUP BY",
 "in" => "IN",
 "on" => "\n\tON",
 "as" => "AS",
 "from" => "\nFROM",
 "join" => "JOIN",
 "inner" => "\n\tINNER",
 "left" => "\n\tLEFT",
 "right" => "\n\tRIGHT",
 "full" => "\n\FULL",
 "uni" => "UNION",
 "count" => "COUNT",
 "avg" => "AVG",
 "sum" => "SUM",
 "min" => "MIN",
 "max" => "MAX",
 "any" => "ANY",
 "all" => "ALL",
 "desc" => "DESC",
 "like" => "LIKE",
 "selc" => "SELECT",
 "selcD" => "SELECT DISTINCT",
 "selcT" => "SELECT TOP",
 "selcI" => "SELECT INTO",
 "upd" => "UPDATE",
 "int" => "INTO",
 "del" => "DELETE",
 "exs" => "EXISTS",
 "where" => "\nWHERE"]);
